import Link from "next/link";
import { ArrowRight, Check, Mail, MapPin } from "lucide-react";
import type { Service } from "@/lib/site-data";

export function Brand(){return <Link href="/" className="brand" aria-label="HezEdge Consulting home"><img src="/hezedge-logo.svg" alt="HezEdge Consulting"/></Link>}
export function SiteHeader(){return <header className="site-header"><div className="shell nav-row"><Brand/><nav aria-label="Primary navigation"><Link href="/#services">Services</Link><Link href="/#approach">How we work</Link><Link href="/#work">Our work</Link><Link href="/about">About</Link></nav><Link className="button button-small button-primary" href="/contact">Discuss your project <ArrowRight size={16}/></Link></div></header>}
export function SiteFooter(){return <footer className="site-footer"><div className="shell footer-grid"><div><Brand/><p>Practical digital solutions designed around your business, customers and ambitions.</p></div><div><h3>Services</h3><Link href="/services/web-app-development">Web & app development</Link><Link href="/services/seo-digital-growth">SEO & digital growth</Link><Link href="/services/ai-business-automation">AI & automation</Link><Link href="/services/cloud-it-infrastructure">Cloud & infrastructure</Link></div><div><h3>Company</h3><Link href="/about">About HezEdge</Link><Link href="/#approach">How we work</Link><Link href="/#work">Selected work</Link><Link href="/contact">Contact</Link></div><div><h3>Start a conversation</h3><a href="mailto:info@hezedge.co.uk"><Mail size={16}/> info@hezedge.co.uk</a><span><MapPin size={16}/> Serving clients internationally</span></div></div><div className="shell footer-bottom"><span>© {new Date().getFullYear()} HezEdge Consulting Limited.</span><span>Technology built around business value.</span></div></footer>}
export function ServiceCard({service}:{service:Service}){const Icon=service.icon;return <article className="service-card"><div className="service-icon"><Icon size={25}/></div><p className="service-kicker">{service.kicker}</p><h3>{service.title}</h3><p>{service.promise}</p><ul>{service.outcomes.slice(0,3).map(item=><li key={item}><Check size={15}/> {item}</li>)}</ul><Link href={`/services/${service.slug}`}>Explore this service <ArrowRight size={17}/></Link></article>}
export function ProofStrip(){return <section className="proof-strip"><div className="shell proof-inner"><div><strong>Built around your business</strong><span>No off-the-shelf assumptions</span></div><div><strong>One connected partner</strong><span>Strategy, delivery and support</span></div><div><strong>Clear communication</strong><span>Practical guidance without jargon</span></div><div><strong>International experience</strong><span>UK, Africa and North America</span></div></div></section>}
