import { Bot, Cloud, Code2, Lightbulb, Search, Workflow } from "lucide-react";

export const services = [
  { slug:"web-app-development", icon:Code2, kicker:"Create and convert", title:"Web & App Development", promise:"Turn business ideas into fast, useful digital experiences.", problem:"Your website no longer represents the business, customers struggle to take action, or an important process needs a purpose-built application.", outcomes:["Conversion-focused websites and ecommerce","Customer portals and custom applications","API, payment and third-party integrations","Hosting, maintenance and technical support"], entry:"Project discovery call", audience:"Businesses launching, replacing or improving a digital product" },
  { slug:"seo-digital-growth", icon:Search, kicker:"Get discovered", title:"SEO & Digital Growth", promise:"Help more of the right customers find and choose your business.", problem:"Competitors outrank you, your website attracts too few qualified enquiries, or you cannot tell which marketing activity is producing value.", outcomes:["Technical and on-page SEO","Local SEO and Google Business Profile","Content and competitor opportunity planning","Plain-language performance reporting"], entry:"Free SEO audit", audience:"Small businesses that depend on search visibility and local demand" },
  { slug:"ai-business-automation", icon:Bot, kicker:"Recover time", title:"AI & Business Automation", promise:"Reduce repetitive work without losing control of the process.", problem:"Your team spends valuable time copying data, chasing follow-ups, preparing routine documents or moving information between systems.", outcomes:["Workflow and automation opportunity review","Lead, email and document automation","Practical AI assistants with human oversight","Monitoring, safeguards and continuous improvement"], entry:"Workflow opportunity review", audience:"Teams with repeatable, time-consuming administrative processes" },
  { slug:"cloud-it-infrastructure", icon:Cloud, kicker:"Operate reliably", title:"Cloud & IT Infrastructure", promise:"Keep your business systems dependable, secure and ready to evolve.", problem:"Unreliable hosting, fragmented infrastructure, weak recovery arrangements or unclear technical ownership is putting continuity at risk.", outcomes:["Cloud setup and workload migration","Application, website and email infrastructure","Backup, monitoring and recovery planning","Ongoing infrastructure support"], entry:"Infrastructure health check", audience:"Businesses that need a reliable foundation for digital operations" },
  { slug:"systems-integration", icon:Workflow, kicker:"Connect operations", title:"Systems Integration", promise:"Make your business tools and information work together.", problem:"Teams repeatedly enter the same data, important systems do not communicate, or manual hand-offs create delays and errors.", outcomes:["Website, CRM, payment and email integration","API and data-flow design","Automatic notifications and reporting","Integration testing and support"], entry:"Integration compatibility review", audience:"Businesses operating across disconnected tools and data sources" },
  { slug:"technology-consulting", icon:Lightbulb, kicker:"Decide with confidence", title:"Technology Consulting", promise:"Choose the right technology before committing your budget.", problem:"You face an important technology decision without an independent view of cost, suitability, risk or long-term implications.", outcomes:["Technology needs assessment","Solution and vendor comparison","Architecture and implementation roadmap","Delivery assurance and project guidance"], entry:"Technology strategy session", audience:"Leaders planning investment, transformation or a complex digital project" }
] as const;
export type Service = (typeof services)[number];
export const testimonials = [
  { quote:"HezEdge took the time to understand our work in renewable energy and turned that into a clear, professional digital presence. The process was organised, responsive and easy to follow from start to finish.", name:"Yemi Ayeni", context:"CorePower Ltd" },
  { quote:"They understood the pace and standards we work to as a digital agency. Their advice was practical, their communication was straightforward, and they were focused on delivering something that genuinely supported our business.", name:"Tola Babalola", context:"Wildreams" },
  { quote:"For an immigration consultancy, clarity and trust are essential. HezEdge helped us present our services in a way that feels credible, accessible and aligned with the people we support.", name:"Kola Y.", context:"KOY Immigration" },
  { quote:"They approached our mental health clinic with care and attention to detail. The team listened closely, communicated clearly and created a digital experience that feels appropriate for our clients.", name:"Dr. Simi A.", context:"Transcend Mental Health & Wellness" },
  { quote:"HezEdge brought structure to our digital needs and made the next steps clear. They were thoughtful, dependable and focused on what would be most useful for our learners and wider community.", name:"Efe O.", context:"Daystar Leadership Academy" },
  { quote:"HezEdge understood that we needed a professional digital presence that reflects the confidence clients place in our advisory work. They were thoughtful, responsive and deliberate about the details that matter.", name:"Adewale Champion", context:"TecInvest Advisory Ltd" }
];
