import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, Check, ChevronRight } from "lucide-react";
import { SiteFooter, SiteHeader } from "@/components/site-shell";
import { services } from "@/lib/site-data";
export function generateStaticParams(){return services.map(service=>({slug:service.slug}))}
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const service=services.find(item=>item.slug===slug);if(!service)notFound();const Icon=service.icon;return <main><SiteHeader/>
<section className="sub-hero"><div className="shell"><div className="breadcrumbs"><Link href="/">Home</Link><ChevronRight size={14}/><span>{service.title}</span></div><div className="sub-hero-grid"><div><p className="eyebrow"><Icon size={16}/> {service.kicker}</p><h1>{service.promise}</h1><p className="lede">{service.problem}</p><div className="hero-actions"><Link className="button button-primary" href={`/contact?service=${service.slug}`}>Book your {service.entry.toLowerCase()} <ArrowRight size={18}/></Link><Link className="button button-secondary" href="/#services">Compare services</Link></div></div><aside className="fit-card"><span>Best suited to</span><h2>{service.audience}</h2><p>Not sure whether this is the right service? Tell us what you are trying to achieve and we will guide you.</p></aside></div></div></section>
<section className="section"><div className="shell service-detail-grid"><div><p className="eyebrow">What we can deliver</p><h2>A solution shaped around the outcome.</h2><p className="lede">The exact scope is agreed after discovery. These are the core capabilities most relevant to this service.</p></div><div className="deliverable-list">{service.outcomes.map((item,index)=><article key={item}><span>0{index+1}</span><div><h3>{item}</h3><p>Defined, implemented and tested in the context of your existing operation and priorities.</p></div></article>)}</div></div></section>
<section className="section section-soft"><div className="shell"><div className="section-heading"><div><p className="eyebrow">What working together looks like</p><h2>Transparent from the first conversation.</h2></div></div><div className="three-col"><article><span>01</span><h3>Understand</h3><p>We clarify your desired outcome, users, current position, constraints and success measures.</p></article><article><span>02</span><h3>Recommend</h3><p>We explain practical options, trade-offs, scope and priorities in language you can act on.</p></article><article><span>03</span><h3>Deliver</h3><p>We implement the agreed solution, communicate progress and provide appropriate handover or support.</p></article></div></div></section>
<section className="decision-section"><div className="shell decision-grid"><div><p className="eyebrow eyebrow-light">Reduce uncertainty</p><h2>Begin with a focused {service.entry.toLowerCase()}.</h2><p>Bring the problem, goal or idea. You do not need to arrive with a technical specification.</p></div><ul><li><Check size={18}/> Clear first conversation</li><li><Check size={18}/> No obligation to proceed</li><li><Check size={18}/> Practical next-step recommendation</li></ul><Link className="button button-white" href={`/contact?service=${service.slug}`}>Get started <ArrowRight size={18}/></Link></div></section><SiteFooter/></main>}
